### PR TITLE
CI: more automation

### PR DESCRIPTION
**Pull request by msimerson**
Changes proposed in this pull request:

- consolidate *nix & win tests
- add package publishing
- disable coveralls, doesn't work in plugins

Checklist:
- [x] docs updated
- [ ] tests updated
- [x] Changes.md updated
- [x] package.json.version bumped

### CODE REVIEW

**Comment by baudehlo** [comment]
This is what I had to do to get coveralls working here:
```
    - name: Generates LCOV report
      if: success()
      run: |
         unset TRAVIS
         ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
         ls -l coverage.lcov

    - name: Coverage check
      uses: devmasx/coverage-check-action@v1.2.0
      if: success()
      with:
        type: lcov
        result_path: coverage.lcov
        min_coverage: 40
        token: ${{ github.token }}

    - name: Coveralls
      if: success()
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: coverage.lcov
        github-token: ${{ github.token }}

```

**Comment by baudehlo** [comment]
(Note that was in-line after the `npm test` stuff)

**Comment by msimerson** [comment]
Coveralls works just fine, it's just that there's no output for plugins due to the vm.runInNewContext() funny business.

**Comment by msimerson** [comment]
As is:

````
✗ cat .nyc_output/03317a73-f3fe-4e6d-ad37-013da9f00161.json
{}%                                                       
````

With your command:

````
$ npx nyc report --reporter=text-lcov > coverage.lcov
➜  haraka-plugin-template git:(more-workflow-automation) ✗ cat coverage.lcov 
➜  haraka-plugin-template git:(more-workflow-automation) ✗ 
````

Same net result.

**Pull request merged**
